#!/bin/sh
set -x

if [ -z "$1" ]; then
    echo "Error: no interface specified"
    exit 1
fi

# Cria a TAP caso ela ainda não exista
if ! ip link show "$1" >/dev/null 2>&1; then
    ip tuntap add "$1" mode tap user "$(whoami)"
fi

# IP fixo da ponta HOST da rede QEMU
ip addr replace 192.168.1.1/24 dev "$1"

# Ativa a interface
ip link set "$1" up

# Permite encaminhamento IPv4
sysctl -w net.ipv4.ip_forward=1

exit 0